---
title: Error Handling
description: Learn how errors are handled
---

import {Callout} from 'nextra/components';

# Error Handling

Kaito handles errors gracefully throughout your application. You can throw errors anywhere in any route, and they will be automatically caught and processed. This allows you to focus on the happy-paths of your application while ensuring proper error handling. The other advantage to this pattern is that you don't have to worry about error messages that could contain sensitive information, as everything passes through your onError handler.

Kaito has a built in error called `KaitoError`. You can throw this error in your routes, and it will be caught and sent back to the client.

<Callout>
	Throwing a `KaitoError` will **not** call your `.onError` handler defined in your server. KaitoErrors are handled
	internally and are always sent back to the client.
</Callout>

```ts filename="routes/users.ts" {8}
export const users = router.get('/:id', async ({ctx, params}) => {
	const user = await ctx.db.users.findOne({
		where: {id: params.id},
	});

	if (!user) {
		// Client will receive this status code and error message always. This bypasses your .onError() handler
		throw new KaitoError(404, 'User not found');
	}

	return user;
});
```

All other errors will be forwarded to your `.onError` handler, which dictates what status and message should be sent to the client.
